#!/usr/bin/env python3
"""Generate static roadmap cards from the owned manuals and topic catalog."""
from __future__ import annotations

import argparse
import copy
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import urljoin, urlsplit

ROOT = Path(__file__).resolve().parents[2]
FENCE = re.compile(r"^```([^\n]*)\n(.*?)^```[ \t]*$", re.M | re.S)
GENERATED_HEADER = "// Generated by tools/roadmap/sync.py; edit the catalog or manuals.\n"


def sections(markdown):
    fenced = [(match.start(), match.end()) for match in FENCE.finditer(markdown)]
    headings = [match for match in re.finditer(r"^## ([^\n]+)\n", markdown, re.M)
                if not any(start <= match.start() < end for start, end in fenced)]
    return [(heading[1], markdown[heading.end():headings[index + 1].start()
             if index + 1 < len(headings) else len(markdown)])
            for index, heading in enumerate(headings)]


def prose(text):
    text = FENCE.sub("", text)
    text = re.sub(r"^> \[![A-Z]+\][ \t]*$", "", text, flags=re.M)
    text = re.sub(r"^> ?", "", text, flags=re.M)
    return [re.sub(r"\s+", " ", paragraph).strip()
            for paragraph in re.split(r"\n\s*\n", text.strip())
            if paragraph.strip() and not paragraph.strip().startswith("**Version")]


def inline(text, base):
    """Render only safe Markdown links/emphasis; escape everything else."""
    parts = re.split(r"(`[^`]+`|\[[^\]]+\]\([^\s)]+\)|\*\*[^*]+\*\*)", text)
    output = []
    for part in parts:
        link = re.fullmatch(r"\[([^\]]+)\]\(([^\s)]+)\)", part)
        if part.startswith("`") and part.endswith("`"):
            output.append("<code>" + html.escape(part[1:-1]) + "</code>")
        elif part.startswith("**") and part.endswith("**"):
            output.append("<strong>" + html.escape(part[2:-2]) + "</strong>")
        elif link and urlsplit(link[2]).scheme in {"", "https", "http"}:
            url = urljoin(base, link[2])
            output.append('<a href="' + html.escape(url, quote=True)
                          + '" target="_blank" rel="noopener">'
                          + html.escape(link[1]) + "</a>")
        else:
            output.append(html.escape(part))
    return "".join(output)


def narrative(body, base):
    """Render manual prose, lists and simple tables without permitting raw HTML."""
    body = FENCE.sub("\n\n", body)
    body = re.sub(r"^> \[![A-Z]+\][ \t]*$", "", body, flags=re.M)
    body = re.sub(r"^> ?", "", body, flags=re.M)
    output = []
    for paragraph in re.split(r"\n\s*\n", body.strip()):
        lines = [line.strip() for line in paragraph.splitlines() if line.strip()]
        if not lines or lines[0].startswith("**Version"):
            continue
        if len(lines) >= 2 and lines[0].startswith("|") and re.fullmatch(r"[| :\-]+", lines[1]):
            rows = [[cell.strip() for cell in line.strip("|").split("|")]
                    for line in [lines[0], *lines[2:]]]
            output.append('<div class="manual-table"><table><thead><tr>'
                          + "".join("<th>" + inline(cell, base) + "</th>" for cell in rows[0])
                          + "</tr></thead><tbody>"
                          + "".join("<tr>" + "".join("<td>" + inline(cell, base) + "</td>"
                                                   for cell in row) + "</tr>" for row in rows[1:])
                          + "</tbody></table></div>")
        elif all(re.match(r"(?:[-*]|\d+\.) ", line) for line in lines):
            tag = "ol" if re.match(r"\d+\. ", lines[0]) else "ul"
            output.append("<" + tag + ">" + "".join("<li>" + inline(
                re.sub(r"^(?:[-*]|\d+\.) ", "", line), base) + "</li>" for line in lines)
                          + "</" + tag + ">")
        elif re.fullmatch(r"\*\*[^*]+\*\*", paragraph.strip()):
            # Command labels are already displayed beside their fenced blocks.
            continue
        elif len(lines) == 1 and lines[0].startswith("### "):
            # Fenced block labels are rendered by the command component.
            continue
        else:
            output.append("<p>" + inline(" ".join(lines), base) + "</p>")
    return "".join(output)


def instructions(body, default_label):
    output = []
    for match in FENCE.finditer(body):
        labels = re.findall(r"^(?:\*\*([^\n]+)\*\*|### ([^\n]+))[ \t]*$",
                            body[:match.start()], re.M)
        label = next((x for x in labels[-1] if x), default_label) if labels else default_label
        output.append({"label": label, "code": match[2].strip("\n")})
    return output


def manual_card(path, metadata, base):
    markdown = path.read_text()
    card = dict(metadata)
    card.update(install=[], run=[], ciExamples=[], notes=[])
    content = sections(markdown)
    purpose = next((body for title, body in content if title == "What it is for"), None)
    if purpose is None:
        # New operational manuals put their introduction before the first H2.
        introduction = markdown.split("\n## ", 1)[0]
        paragraphs = [p for p in prose(introduction)
                      if not p.startswith(("#", "**", "["))]
    else:
        paragraphs = prose(purpose)
    card["role"] = re.sub(r"`([^`]+)`", r"\1", paragraphs[0]) if paragraphs else metadata["name"]
    card["why"] = "<p>" + "</p><p>".join(inline(p, base) for p in paragraphs) + "</p>"
    versions = re.findall(r"^\*\*(?:Version[^*]*|Versions[^*]*):\*\* ([^\n]+)", markdown, re.M)
    if versions:
        card["versionInfo"] = inline(versions[0], base)
    for title, body in content:
        blocks = instructions(body, title)
        if title.startswith("Install"):
            card["install"].extend(blocks)
            card["installNotes"] = narrative(body, base)
        elif title == "Use":
            card["run"].extend(blocks)
            card["runNotes"] = narrative(body, base)
        elif title == "CI example":
            card["ciExamples"].extend(blocks)
            card["ciNotes"] = narrative(body, base)
        elif title == "Output and triage":
            card["results"] = narrative(body, base)
        elif title not in {"What it is for", "Concepts to know", "Related tools"}:
            card["run"].extend(blocks)
            paragraphs = prose(body)
            if paragraphs:
                card["notes"].append({"title": title, "html": narrative(body, base)})
    return card


def build(root=ROOT, catalog=None):
    catalog = copy.deepcopy(catalog if catalog is not None else
                            json.loads((root / "tools/roadmap/catalog.json").read_text()))
    errors = []
    areas = catalog["areas"]
    stages = catalog["stages"]
    tools = [tool for stage in stages for tool in stage["tools"]]
    for name, objects in (("area", areas), ("topic", stages), ("tool", tools)):
        ids = [item["id"] for item in objects]
        if len(ids) != len(set(ids)):
            errors.append(f"duplicate {name} ID")
        if any(not re.fullmatch(r"[a-z0-9-]+", identifier) for identifier in ids):
            errors.append(f"invalid {name} ID")
    linked_stages = [identifier for area in areas for identifier in area["stages"]]
    if sorted(linked_stages) != sorted(stage["id"] for stage in stages):
        errors.append("every topic must belong to exactly one area")
    manuals = {path.stem for path in (root / "manuals").glob("*.md")
               if path.name not in {"README.md", "TEMPLATE.md"}}
    ids = {tool["id"] for tool in tools}
    if ids != manuals:
        errors.append(f"manual/catalog mismatch: missing={sorted(manuals - ids)}, extra={sorted(ids - manuals)}")
    controls = json.loads((root / "baseline/controls.json").read_text())["controls"]
    control_ids = {control["id"] for control in controls}
    mapped = {identifier for stage in stages for identifier in stage.get("controlIds", [])}
    if mapped != control_ids:
        errors.append(f"baseline coverage mismatch: missing={sorted(control_ids - mapped)}, unknown={sorted(mapped - control_ids)}")
    phases = {phase["id"] for phase in catalog["phases"]}
    for stage in stages:
        if stage["phase"] not in phases:
            errors.append(f"{stage['id']}: unknown phase")
        for resource in stage.get("resources", []):
            path = root / resource["path"]
            if not path.resolve().is_relative_to(root.resolve()) or not path.is_file():
                errors.append(f"{stage['id']}: missing or invalid resource {resource['path']}")
        for tool in stage["tools"]:
            if tool.get("repoPath") and not (root / tool["repoPath"]).exists():
                errors.append(f"{tool['id']}: missing repository path {tool['repoPath']}")
            if set(tool) & {"install", "run", "ci", "github", "ciExamples", "results", "why",
                            "installNotes", "runNotes", "ciNotes", "notes", "versionInfo"}:
                errors.append(f"{tool['id']}: instructions must come from the manual")
    if errors:
        raise ValueError("\n".join(errors))
    catalog["controls"] = [{key: control[key] for key in ("id", "title", "owner_role")}
                           for control in controls]
    catalog["fileBase"] = catalog["manualBase"].removesuffix("manuals/")
    for stage in stages:
        stage["tools"] = [manual_card(root / "manuals" / (tool["id"] + ".md"), tool,
                                      catalog["manualBase"] + tool["id"] + ".md")
                          for tool in stage["tools"]]
    return GENERATED_HEADER + "window.ROADMAP = " + json.dumps(catalog, indent=2, ensure_ascii=False) + ";\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed site differs from its sources")
    args = parser.parse_args()
    try:
        expected = build()
        destination = ROOT / "public/data.js"
        if args.check:
            if not destination.exists() or destination.read_text() != expected:
                raise ValueError("Roadmap is stale. Run: python3 tools/roadmap/sync.py")
            print("Roadmap manuals, topic links and baseline coverage: OK")
        else:
            destination.write_text(expected)
            print("Updated public/data.js from all manuals and baseline controls")
        return 0
    except (ValueError, KeyError, OSError) as exc:
        print(exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
